/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    'service-categories': ServiceCategory;
    products: Product;
    projects: Project;
    testimonials: Testimonial;
    awards: Award;
    careers: Career;
    posts: Post;
    pages: Page;
    'contact-submissions': ContactSubmission;
    subscribers: Subscriber;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-categories': ServiceCategoriesSelect<false> | ServiceCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * One line under the title. Shown on cards and the hero.
   */
  tagline: string;
  /**
   * The card blurb on the services grid and home page.
   */
  summary: string;
  icon:
    | 'code-2'
    | 'server'
    | 'palette'
    | 'megaphone'
    | 'shopping-cart'
    | 'shield-check'
    | 'cloud'
    | 'cpu'
    | 'database'
    | 'smartphone'
    | 'network'
    | 'bot';
  category?: (number | null) | ServiceCategory;
  /**
   * The main narrative on the service detail page.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What this service includes. 3–8 works best.
   */
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Concrete artefacts the client receives.
   */
  deliverables?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  techStack?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Rendered as an accordion and as FAQ structured data.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Falls back to the page title and site defaults when empty.
   */
  seo?: {
    /**
     * Browser tab and search result headline. Aim for under 60 characters.
     */
    title?: string | null;
    /**
     * Search result snippet. Aim for 140–160 characters.
     */
    description?: string | null;
    /**
     * Social share image. 1200×630 recommended.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  /**
   * Leave blank to generate from the title. Avoid changing it once the page is live.
   */
  slug: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Highlight on the home page.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories".
 */
export interface ServiceCategory {
  id: number;
  name: string;
  /**
   * Leave blank to generate from the title. Avoid changing it once the page is live.
   */
  slug: string;
  /**
   * Shown on category filter chips and listing intros.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines. For purely decorative images, write "decorative".
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * One line under the name. What it does, in plain words.
   */
  tagline: string;
  /**
   * The card blurb on the products index and home page.
   */
  summary: string;
  productType: 'wordpress-plugin' | 'web-app' | 'mobile-app' | 'desktop-app' | 'solution';
  /**
   * Shown as badges. Leave empty if not meaningful.
   */
  platforms?: ('web' | 'wordpress' | 'ios' | 'android' | 'windows' | 'macos' | 'linux' | 'self-hosted')[] | null;
  availability: 'live' | 'beta' | 'coming-soon';
  logo?: (number | null) | Media;
  /**
   * Screenshot or hero image for the product page.
   */
  coverImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What it does. 3–8 works best.
   */
  features?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Label/value pairs — version, PHP requirement, minimum OS, licence. Rendered as a table.
   */
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  pricing?: {
    currency?: ('USD' | 'BDT' | 'EUR' | 'GBP') | null;
    tiers?:
      | {
          name: string;
          priceType: 'fixed' | 'free' | 'custom';
          /**
           * Number only — the currency symbol is added automatically.
           */
          price?: number | null;
          period?: ('month' | 'year' | 'once') | null;
          /**
           * e.g. "per site" or "up to 10 users"
           */
          priceNote?: string | null;
          description?: string | null;
          features?:
            | {
                item: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Emphasise this plan. Use on at most one.
           */
          highlighted?: boolean | null;
          /**
           * e.g. "Most popular"
           */
          badge?: string | null;
          ctaLabel?: string | null;
          /**
           * Leave blank to link to the quote form.
           */
          ctaHref?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Shown under the plans — VAT, refund policy, and so on.
     */
    note?: string | null;
  };
  links?: {
    website?: string | null;
    demo?: string | null;
    docs?: string | null;
    wordpressOrg?: string | null;
    appStore?: string | null;
    playStore?: string | null;
    download?: string | null;
    github?: string | null;
  };
  /**
   * Optional. Falls back to the page title and site defaults when empty.
   */
  seo?: {
    /**
     * Browser tab and search result headline. Aim for under 60 characters.
     */
    title?: string | null;
    /**
     * Search result snippet. Aim for 140–160 characters.
     */
    description?: string | null;
    /**
     * Social share image. 1200×630 recommended.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  /**
   * Leave blank to generate from the title. Avoid changing it once the page is live.
   */
  slug: string;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Only publish a client name you have permission to use.
   */
  client: string;
  /**
   * The card blurb on the work index.
   */
  summary: string;
  coverImage: number | Media;
  industry?:
    | (
        | 'Finance & Fintech'
        | 'Healthcare'
        | 'Logistics & Supply Chain'
        | 'Retail & E-Commerce'
        | 'Education'
        | 'Government & NGO'
        | 'Manufacturing'
        | 'Real Estate'
        | 'Media & Entertainment'
      )
    | null;
  /**
   * Which of our services this project drew on.
   */
  services?: (number | Service)[] | null;
  /**
   * Year of delivery. Drives the default sort order.
   */
  year?: number | null;
  /**
   * Live site or app store link, if public.
   */
  url?: string | null;
  challenge?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  results?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Hard numbers. These do more selling than any paragraph.
   */
  metrics?:
    | {
        /**
         * e.g. "3.2×" or "−41%"
         */
        value: string;
        /**
         * e.g. "faster checkout"
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  techStack?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Falls back to the page title and site defaults when empty.
   */
  seo?: {
    /**
     * Browser tab and search result headline. Aim for under 60 characters.
     */
    title?: string | null;
    /**
     * Search result snippet. Aim for 140–160 characters.
     */
    description?: string | null;
    /**
     * Social share image. 1200×630 recommended.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  /**
   * Leave blank to generate from the title. Avoid changing it once the page is live.
   */
  slug: string;
  /**
   * Show on the home page.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * e.g. "Head of Operations"
   */
  role?: string | null;
  company: string;
  /**
   * Publish only quotes you actually received and may attribute.
   */
  quote: string;
  avatar?: (number | null) | Media;
  companyLogo?: (number | null) | Media;
  /**
   * Links the quote to its case study.
   */
  project?: (number | null) | Project;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  title: string;
  organization?: string | null;
  year?: number | null;
  description?: string | null;
  logo?: (number | null) | Media;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  department: 'Engineering' | 'Design' | 'Infrastructure' | 'Marketing' | 'Sales' | 'Operations';
  /**
   * e.g. "Dhaka, Bangladesh" or "Remote"
   */
  location: string;
  workplace: 'on-site' | 'hybrid' | 'remote';
  employmentType: 'full-time' | 'part-time' | 'contract' | 'internship';
  level?: ('Intern' | 'Junior' | 'Mid-level' | 'Senior' | 'Lead') | null;
  /**
   * Optional but strongly recommended — listings with pay ranges get far more applicants.
   */
  salaryRange?: string | null;
  deadline?: string | null;
  /**
   * Where applications for this role should be sent.
   */
  applyEmail?: string | null;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  responsibilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Falls back to the page title and site defaults when empty.
   */
  seo?: {
    /**
     * Browser tab and search result headline. Aim for under 60 characters.
     */
    title?: string | null;
    /**
     * Search result snippet. Aim for 140–160 characters.
     */
    description?: string | null;
    /**
     * Social share image. 1200×630 recommended.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  /**
   * Leave blank to generate from the title. Avoid changing it once the page is live.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Shown on the insights index and in search results.
   */
  excerpt: string;
  coverImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. Falls back to the page title and site defaults when empty.
   */
  seo?: {
    /**
     * Browser tab and search result headline. Aim for under 60 characters.
     */
    title?: string | null;
    /**
     * Search result snippet. Aim for 140–160 characters.
     */
    description?: string | null;
    /**
     * Social share image. 1200×630 recommended.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  /**
   * Leave blank to generate from the title. Avoid changing it once the page is live.
   */
  slug: string;
  publishedAt: string;
  author?: (number | null) | User;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Optional line under the page heading.
   */
  subtitle?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Leave blank to generate from the title. Avoid changing it once the page is live.
   */
  slug: string;
  /**
   * Optional. Falls back to the page title and site defaults when empty.
   */
  seo?: {
    /**
     * Browser tab and search result headline. Aim for under 60 characters.
     */
    title?: string | null;
    /**
     * Search result snippet. Aim for 140–160 characters.
     */
    description?: string | null;
    /**
     * Social share image. 1200×630 recommended.
     */
    image?: (number | null) | Media;
    /**
     * Hide this page from search engines.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  subject?: string | null;
  message: string;
  serviceInterest?: (number | Service)[] | null;
  budget?: ('Under $5k' | '$5k – $15k' | '$15k – $50k' | '$50k – $150k' | '$150k+' | 'Not sure yet') | null;
  timeline?: ('ASAP' | 'Within 1 month' | '1–3 months' | '3–6 months' | 'Just exploring') | null;
  source?: ('contact' | 'quote') | null;
  status?: ('new' | 'contacted' | 'qualified' | 'won' | 'closed') | null;
  /**
   * Never shown to the sender.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  name?: string | null;
  /**
   * Set when the subscriber confirms via the opt-in email.
   */
  confirmedAt?: string | null;
  /**
   * Set on unsubscribe. Suppress these when sending.
   */
  unsubscribedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-categories';
        value: number | ServiceCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  summary?: T;
  icon?: T;
  category?: T;
  body?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  techStack?:
    | T
    | {
        name?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  slug?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-categories_select".
 */
export interface ServiceCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  summary?: T;
  productType?: T;
  platforms?: T;
  availability?: T;
  logo?: T;
  coverImage?: T;
  body?: T;
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        currency?: T;
        tiers?:
          | T
          | {
              name?: T;
              priceType?: T;
              price?: T;
              period?: T;
              priceNote?: T;
              description?: T;
              features?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              highlighted?: T;
              badge?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
            };
        note?: T;
      };
  links?:
    | T
    | {
        website?: T;
        demo?: T;
        docs?: T;
        wordpressOrg?: T;
        appStore?: T;
        playStore?: T;
        download?: T;
        github?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  slug?: T;
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  summary?: T;
  coverImage?: T;
  industry?: T;
  services?: T;
  year?: T;
  url?: T;
  challenge?: T;
  solution?: T;
  results?: T;
  metrics?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  techStack?:
    | T
    | {
        name?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  slug?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  quote?: T;
  avatar?: T;
  companyLogo?: T;
  project?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  title?: T;
  organization?: T;
  year?: T;
  description?: T;
  logo?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  location?: T;
  workplace?: T;
  employmentType?: T;
  level?: T;
  salaryRange?: T;
  deadline?: T;
  applyEmail?: T;
  summary?: T;
  description?: T;
  responsibilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        item?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  slug?: T;
  publishedAt?: T;
  author?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  content?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  subject?: T;
  message?: T;
  serviceInterest?: T;
  budget?: T;
  timeline?: T;
  source?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline: string;
  /**
   * Default meta description for pages without their own.
   */
  description: string;
  logo?: (number | null) | Media;
  /**
   * Light-coloured mark for use on dark backgrounds.
   */
  logoDark?: (number | null) | Media;
  ogImage?: (number | null) | Media;
  email: string;
  supportEmail?: string | null;
  phone?: string | null;
  whatsapp?: string | null;
  address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * Registered company name, used in the footer and JSON-LD.
   */
  legalName?: string | null;
  registrationNumber?: string | null;
  /**
   * e.g. "Sun–Thu, 9:00–18:00 (GMT+6)"
   */
  businessHours?: string | null;
  social?:
    | {
        platform: 'linkedin' | 'github' | 'x' | 'facebook' | 'instagram' | 'youtube' | 'dribbble' | 'behance';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. G-XXXXXXXXXX. Leave blank to disable.
   */
  googleAnalyticsId?: string | null;
  /**
   * Search Console verification token.
   */
  googleSiteVerification?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Top navigation. Add children to turn an item into a dropdown.
   */
  header?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Text on the header call-to-action button.
   */
  ctaLabel?: string | null;
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  logoDark?: T;
  ogImage?: T;
  email?: T;
  supportEmail?: T;
  phone?: T;
  whatsapp?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  legalName?: T;
  registrationNumber?: T;
  businessHours?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  googleAnalyticsId?: T;
  googleSiteVerification?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  footer?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}