import type { SerializedEditorState } from '@payloadcms/richtext-lexical/lexical'
import {
  type JSXConvertersFunction,
  RichText as PayloadRichText,
} from '@payloadcms/richtext-lexical/react'

import { headingId } from '@/lib/toc'
import { cn } from '@/lib/utils'

/**
 * Adds anchor ids to headings so a table of contents can link into the body.
 * Ids are generated by the same helper `buildToc` uses, and the counter is
 * created per render so duplicate headings resolve identically in both.
 */
const withHeadingIds = (): JSXConvertersFunction => {
  return ({ defaultConverters }) => {
    const seen = new Map<string, number>()

    return {
      ...defaultConverters,
      heading: ({ node, nodesToJSX }) => {
        const children = nodesToJSX({ nodes: node.children })
        const Tag = node.tag as 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'

        // Only h2/h3 appear in the contents list; give ids to those alone so
        // the counters in both places stay in step.
        if (Tag !== 'h2' && Tag !== 'h3') return <Tag>{children}</Tag>

        const text = node.children
          ?.map((child) => ('text' in child && typeof child.text === 'string' ? child.text : ''))
          .join('')
          .trim()

        return (
          <Tag id={text ? headingId(text, seen) : undefined} className="scroll-mt-28">
            {children}
          </Tag>
        )
      },
    }
  }
}

const headingConverters = withHeadingIds()

/**
 * Renders Lexical content from the CMS. Typography is applied through a
 * `prose-*` style block below rather than the Tailwind typography plugin,
 * so the dark palette stays under our control.
 */
export function RichText({
  data,
  className,
  anchors = false,
}: {
  data?: SerializedEditorState | null
  className?: string
  /** Add ids to h2/h3 so a table of contents can link to them. */
  anchors?: boolean
}) {
  if (!data) return null

  return (
    <div
      className={cn(
        'max-w-3xl',
        '[&_h2]:mt-12 [&_h2]:mb-4 [&_h2]:font-display [&_h2]:text-2xl [&_h2]:font-semibold',
        '[&_h3]:mt-9 [&_h3]:mb-3 [&_h3]:font-display [&_h3]:text-xl [&_h3]:font-medium',
        '[&_h4]:mt-7 [&_h4]:mb-2 [&_h4]:font-display [&_h4]:text-lg [&_h4]:font-medium',
        '[&_p]:mb-5 [&_p]:leading-[1.75] [&_p]:text-fg-muted',
        '[&_ul]:mb-6 [&_ul]:flex [&_ul]:list-none [&_ul]:flex-col [&_ul]:gap-2.5 [&_ul]:pl-0',
        '[&_ol]:mb-6 [&_ol]:flex [&_ol]:list-decimal [&_ol]:flex-col [&_ol]:gap-2.5 [&_ol]:pl-5',
        '[&_li]:leading-relaxed [&_li]:text-fg-muted',
        // Bullets drawn as a pseudo-element so they can take the accent colour
        '[&_ul>li]:relative [&_ul>li]:pl-6',
        "[&_ul>li]:before:absolute [&_ul>li]:before:top-[0.6em] [&_ul>li]:before:left-1 [&_ul>li]:before:size-1.5 [&_ul>li]:before:rounded-full [&_ul>li]:before:bg-accent [&_ul>li]:before:content-['']",
        '[&_a]:text-accent [&_a]:underline [&_a]:underline-offset-4 hover:[&_a]:text-accent-hover',
        '[&_strong]:font-semibold [&_strong]:text-fg',
        '[&_blockquote]:my-6 [&_blockquote]:border-l-2 [&_blockquote]:border-accent [&_blockquote]:pl-5 [&_blockquote]:text-fg-muted [&_blockquote]:italic',
        '[&_code]:rounded [&_code]:bg-elevated [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:font-mono [&_code]:text-sm [&_code]:text-accent',
        '[&>*:first-child]:mt-0',
        className,
      )}
    >
      <PayloadRichText data={data} {...(anchors ? { converters: headingConverters } : {})} />
    </div>
  )
}
